In [1]:
import numpy as np

In [16]:
arr = np.array([[2,1,3,4],[5,3,2,7]])
for x in np.nditer(arr, flags = ["buffered"], op_dtypes= ["S"]):
    print(x)

np.bytes_(b'2')
np.bytes_(b'1')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')
np.bytes_(b'3')
np.bytes_(b'2')
np.bytes_(b'7')


In [19]:
np.array([range(i, i+3)for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [29]:
arr = np.array([range(i, i+3)for i in [2,4,6]])
np.zeros(5, dtype ="int64", order = 'C')


array([0, 0, 0, 0, 0])

In [4]:
import numpy as np

# Thiết lập seed
np.random.seed(0)

# Sinh 5 số ngẫu nhiên từ phân phối đều từ 0 đến 1
random_numbers = np.random.rand(5)
print(random_numbers)




[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]


In [18]:
x2 = np. array([[12, 5, 2, 4],[ 7, 6, 8, 8],[ 1, 6, 7, 7]])
x2[np.newaxis, :]

array([[[12,  5,  2,  4],
        [ 7,  6,  8,  8],
        [ 1,  6,  7,  7]]])